#ifndef APP_RESOURCES_H
#define APP_RESOURCES_H

typedef enum PulseResource {
    IMAGE_NULL,
    IMAGE_BLUETOOTH_NO,
    IMAGE_FULLSCREEN_EMAIL,
    IMAGE_MSGLIST_EMAIL_GLOW,
    IMAGE_MSGLIST_EMAIL_NOGLOW,
    FONT_NULL,
    FONT_GEORGIA_10,
    FONT_GOOD_TIMES_26,
    NUM_PULSE_RESOURCES
};

#endif

